title: The Open Source Survey
email: hello@opensourcesurvey.io

description: 3 minute survey to identify priorities and challenges of the open-source community.

baseurl: ""
url: ""

markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-autoprefixer

survey_submit_url: https://4ewtaicfa5.execute-api.us-east-1.amazonaws.com/opensourcesurvey_submit
