title: The Open Source Survey
email: hello@opensourcesurvey.io

description: Take a 3-minute survey to identify priorities and challenges of the open-source community.
twitter_handle: "@osssurvey"

baseurl: ""
url: "https://opensourcesurvey.io"

markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-autoprefixer

survey_submit_url: https://4ewtaicfa5.execute-api.us-east-1.amazonaws.com/opensourcesurvey_submit
